(()=>{"use strict";
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const settings=window.LEAGUE_SETTINGS, data=window.WEEK_DATA;
if(!settings||!data?.players){document.body.innerHTML='<p class="message">Dashboard data could not be loaded.</p>';return}
const players=data.players, byId=id=>players.find(p=>p.id===id), gameFor=p=>data.games.find(g=>g.id===p.game);
const recommended=Object.fromEntries(players.filter(p=>p.slot).map(p=>[p.id,p.slot]));
let lineup=loadLineup(), sort={key:"",dir:-1}, expanded=null, compared=new Set();
function loadLineup(){try{const saved=JSON.parse(localStorage.getItem("dp-lineup-w1"));return validate(saved).ok?saved:{...recommended}}catch{return {...recommended}}}
function counts(map){return Object.values(map||{}).reduce((a,x)=>(a[x]=(a[x]||0)+1,a),{})}
function validate(map){if(!map||typeof map!=="object")return{ok:false,msg:"Invalid saved lineup."};const c=counts(map);for(const [id,slot] of Object.entries(map)){const p=byId(id);if(!p||!(p.pos===slot||(slot==="FLEX"&&settings.flexEligible.includes(p.pos))))return{ok:false,msg:`${p?.name||id} is not eligible for ${slot}.`}}const ok=Object.keys(map).length===9&&c.QB===1&&c.RB===2&&c.WR===2&&c.TE===1&&c.FLEX===2&&c["D/ST"]===1;return{ok,msg:ok?"Legal 9-player lineup.":"Lineup must contain 1 QB, 2 RB, 2 WR, 1 TE, 2 FLEX and 1 D/ST."}}
function save(){localStorage.setItem("dp-lineup-w1",JSON.stringify(lineup))}
function fmt(v,kind="text"){if(v===null||v===undefined||v==="")return'<span class="pending">Pending</span>';if(kind==="pts")return Number(v).toFixed(1);return String(v)}
function implied(p){const g=gameFor(p);if(!g)return null;return (g.current.total+(p.team===g.favorite?g.current.spread:-g.current.spread))/2}
function oppImplied(p){const g=gameFor(p);return g?g.current.total-implied(p):null}
function playerSpread(p){const g=gameFor(p);return g?(p.team===g.favorite?-g.current.spread:g.current.spread):null}
function movement(g){const sd=g.current.spread-g.previous.spread,td=g.current.total-g.previous.total;return !sd&&!td?"No change":[sd?`spread ${sd>0?"+":""}${sd}`:"",td?`total ${td>0?"+":""}${td}`:""].filter(Boolean).join(" · ")}
function badge(p){const y=p.injury!=="Healthy";return `<span class="badge ${y?'yellow':''}">${p.injury}</span>`}
function renderHeader(){const starters=Object.keys(lineup).map(byId);const projections=starters.map(p=>p.expected);const total=projections.every(Number.isFinite)?projections.reduce((a,b)=>a+b,0):null;$("#total").textContent=total===null?"Pending":total.toFixed(1);$("#law-count").textContent=projections.every(Number.isFinite)?projections.filter(x=>x>=10).length:"Pending";const risky=starters.filter(p=>p.risk==="High"||p.injury!=="Healthy").length;$("#risk-count").textContent=risky;let health=total!==null&&total>96&&risky<2?["Safe","var(--green)"]:total!==null&&total<90?["At risk","var(--red)"]:["Monitor · data pending","var(--yellow)"];$("#health-label").textContent=health[0];$("#health-dot").style.background=health[1];$("#updated").textContent=`Data last updated ${new Date(settings.updatedAt).toLocaleString([], {dateStyle:"medium",timeStyle:"short",timeZone:"UTC"})} UTC`;$("#week").textContent=settings.week}
function slotOrder(){const used={};return settings.slots.map(slot=>{used[slot]=(used[slot]||0)+1;const ids=Object.keys(lineup).filter(id=>lineup[id]===slot);return{id:ids[used[slot]-1],slot,label:slot+(counts(settings.slots)[slot]>1?` ${used[slot]}`:"")}})}
function renderLineup(){const allCounts=counts(settings.slots);let seen={};$("#lineup-grid").innerHTML=settings.slots.map(slot=>{seen[slot]=(seen[slot]||0)+1;const ids=Object.keys(lineup).filter(id=>lineup[id]===slot);const id=ids[seen[slot]-1],p=byId(id);if(!p)return"";const eligible=players.filter(x=>x.pos===slot||(slot==="FLEX"&&settings.flexEligible.includes(x.pos)));return `<article class="player-card ${p.recommendation==='Monitor'?'monitor':''}"><div class="card-top"><span class="slot">${slot}${allCounts[slot]>1?' '+seen[slot]:''}</span>${badge(p)}</div><h3>${p.name}</h3><p>${p.team} · ${p.home?'vs':'@'} ${p.opp} · ${new Date(p.kickoff).toLocaleString([], {weekday:'short',hour:'numeric',minute:'2-digit',timeZone:'UTC'})} UTC</p><p>${p.role}</p><div class="card-stats"><span>RANGE<b>${fmt(p.floor,'pts')}–${fmt(p.ceiling,'pts')}</b></span><span>LAW OF 10<b>${p.confidence}</b></span><span>IMPLIED<b>${implied(p).toFixed(2)}</b></span></div><div class="card-actions"><select data-swap="${id}" data-slot="${slot}" aria-label="Replace ${p.name}">${eligible.map(x=>`<option value="${x.id}" ${x.id===id?'selected':''}>${x.name}</option>`).join('')}</select><button data-detail="${id}">Evidence →</button></div></article>`}).join("");$("#lineup-message").textContent=validate(lineup).msg;$$('[data-swap]').forEach(s=>s.onchange=()=>swap(s.dataset.swap,s.value,s.dataset.slot));$$('[data-detail]').forEach(b=>b.onclick=()=>openDetail(b.dataset.detail))}
function swap(oldId,newId,slot){if(oldId===newId)return;const otherSlot=lineup[newId];delete lineup[oldId];if(otherSlot){delete lineup[newId];lineup[oldId]=otherSlot}lineup[newId]=slot;const v=validate(lineup);if(!v.ok){lineup={...recommended};$("#lineup-message").textContent=v.msg+" Reset applied."}save();renderAll()}
const battles=[{title:"QB decision",ids:["hurts","goff"],winner:"Hurts"},{title:"TE / FLEX pivot",ids:["kittle","warren","henry"],winner:"Kittle, only without restriction"},{title:"FLEX pool",ids:["warren","burden","shakir","meyers","brob","henry","sampson"],winner:"Warren if healthy"}];
function renderBattles(){$("#battle-grid").innerHTML=battles.map(b=>`<article class="battle"><p class="eyebrow">${b.ids.length}-PLAYER READ</p><h3>${b.title}</h3>${b.ids.map(id=>{const p=byId(id);return `<div class="battle-row"><label><input type="checkbox" data-compare="${id}" ${compared.has(id)?'checked':''}> <b>${p.name}</b><small>${p.injury} · ${p.role}</small></label><span>${p.confidence}<small>Floor / Exp / Ceiling: ${fmt(p.floor)} / ${fmt(p.expected)} / ${fmt(p.ceiling)}</small></span></div>`}).join('')}<p class="winner">Recommended: ${b.winner}</p></article>`).join('');$$('[data-compare]').forEach(c=>c.onchange=()=>{c.checked?compared.add(c.dataset.compare):compared.delete(c.dataset.compare);if(compared.size>3){compared.delete(c.dataset.compare);c.checked=false}$("#compare-count").textContent=compared.size})}
function renderGames(){$("#game-grid").innerHTML=data.games.map(g=>{const fav=(g.current.total+g.current.spread)/2, dog=(g.current.total-g.current.spread)/2, ps=players.filter(p=>p.game===g.id);return `<article class="game"><p class="eyebrow">CURRENT MARKET</p><h3>${g.matchup}</h3><div class="game-line"><span><small>SPREAD</small><b>${g.favorite} -${g.current.spread}</b></span><span><small>TOTAL</small><b>${g.current.total}</b></span><span><small>IMPLIED</small><b>${g.favorite} ${fav.toFixed(2)} · ${g.underdog} ${dog.toFixed(2)}</b></span></div><p class="movement">↗ ${movement(g)}</p><p>${ps.map(p=>`<b>${p.name}</b> — ${movement(g)==='No change'?'neutral':g.current.total<g.previous.total?'hurts environment':'helps environment'}`).join('<br>')}</p></article>`}).join('')}
function sourceLinks(p){return p.sources?.length?p.sources.map(s=>`<a href="${s.url}" target="_blank" rel="noopener">${s.label}</a>`).join(', '):fmt(null)}
function row(p){const starter=lineup[p.id];return `<tr data-row="${p.id}"><td><input type="checkbox" data-compare="${p.id}" aria-label="Compare ${p.name}" ${compared.has(p.id)?'checked':''}></td><td>${p.name}</td><td>${p.pos}</td><td><button data-toggle="${p.id}" class="${starter?'':'ghost'}">${starter||'Bench'}</button></td><td>${p.home?'vs':'@'} ${p.opp}</td><td>${playerSpread(p)>0?'+':''}${playerSpread(p)}</td><td>${gameFor(p)?.current.total}</td><td>${implied(p)?.toFixed(2)}</td><td>${oppImplied(p)?.toFixed(2)}</td><td>${movement(gameFor(p))}</td><td>${fmt(p.props)}</td><td>${p.role}</td><td>${fmt(p.previousSnapPct)}</td><td>${fmt(p.routes)}</td><td>${fmt(p.carries)}</td><td>${fmt(p.targets)}</td><td>${fmt(p.redZoneOpportunities)}</td><td>${fmt(p.workloadDirection)}</td><td>${badge(p)}</td><td>${fmt(p.practice)}</td><td>${fmt(p.teammateInjuries)}</td><td>${fmt(p.offensiveLine)}</td><td>${fmt(p.defensiveInjuries)}</td><td>${fmt(p.matchupRank)}</td><td>${fmt(p.runPassMatchup)}</td><td>${p.script}</td><td>${p.history}</td><td>${p.form}</td><td>${p.home?'Home':'Away'}</td><td>${p.venue}</td><td>${fmt(p.weather)}</td><td>${fmt(p.travel)}</td><td>${fmt(p.lockConcern)}</td><td class="return">${fmt(p.kickoffReturn)}</td><td class="return">${fmt(p.puntReturn)}</td><td>${fmt(p.floor)}</td><td>${fmt(p.expected)}</td><td>${fmt(p.ceiling)}</td><td><span class="pill">${p.confidence}</span></td><td>${p.risk}</td><td>${p.recommendation}</td><td>${p.notes}</td><td>${sourceLinks(p)}</td></tr>${expanded===p.id?detailRow(p):''}`}
function detailRow(p){return `<tr class="detail-row"><td colspan="43"><div class="detail-grid"><article><h4>Vegas outlook · calculated</h4><p>${p.team} ${playerSpread(p)>0?'+':''}${playerSpread(p)} · total ${gameFor(p).current.total}<br>Team implied ${implied(p).toFixed(2)} · opponent ${oppImplied(p).toFixed(2)}<br>${movement(gameFor(p))}</p></article><article><h4>Role & availability · report fact</h4><p>${p.role}. ${p.availability}</p><p>Practice: ${fmt(p.practice)}</p></article><article><h4>Matchup & history · report fact</h4><p>2025 positional rank: ${fmt(p.matchupRank)}. ${p.script}</p><p>${p.history}</p></article><article><h4>Recent form & conditions</h4><p>${p.form}</p><p>${p.venue}; weather ${fmt(p.weather)}. Return: ${p.returnRole}.</p></article><article><h4>Final reasoning · analyst assessment</h4><p><b>${p.recommendation}</b> · ${p.confidence} Law-of-10 confidence · ${p.risk} risk.</p><p>${p.notes}</p></article><article><h4>Source links</h4>${sourceLinks(p)}</article></div></td></tr>`}
function filtered(){let out=players.filter(p=>{const status=lineup[p.id]?"Starter":"Bench",q=$("#search").value.toLowerCase();return(!q||`${p.name} ${p.team}`.toLowerCase().includes(q))&&(!$("#status-filter").value||status===$("#status-filter").value)&&(!$("#position-filter").value||p.pos===$("#position-filter").value)&&(!$("#injury-filter").value||p.injury===$("#injury-filter").value)&&(!$("#rec-filter").value||p.recommendation===$("#rec-filter").value)&&(!$("#confidence-filter").value||p.confidence===$("#confidence-filter").value)&&(!$("#window-filter").value||p.window===$("#window-filter").value)&&(!$("#special-filter").value||($("#special-filter").value==='return'&&p.returnRole!=="None"&&p.returnRole!=="N/A")||($("#special-filter").value==='missing'&&[p.props,p.practice,p.weather,p.routes].some(x=>x==null))) });if(sort.key){const order={Low:1,Medium:2,High:3,Strong:4,"Injury-dependent":2};out.sort((a,b)=>{const val=p=>sort.key==='implied'?implied(p):sort.key==='spread'?playerSpread(p):sort.key==='rank'?p.matchupRank:sort.key==='confidence'?order[p.confidence]:sort.key==='risk'?order[p.risk]:p[sort.key];return ((val(a)??-Infinity)-(val(b)??-Infinity))*sort.dir})}return out}
function renderTable(){const rows=filtered();$("#player-rows").innerHTML=rows.map(row).join('');$("#row-count").textContent=`Showing ${rows.length} of ${players.length} players`;$$('[data-row]').forEach(r=>r.onclick=e=>{if(e.target.closest('button,input,a'))return;expanded=expanded===r.dataset.row?null:r.dataset.row;renderTable()});$$('[data-toggle]').forEach(b=>b.onclick=e=>{e.stopPropagation();toggleStarter(b.dataset.toggle)});$$('[data-compare]').forEach(c=>c.onchange=()=>{c.checked?compared.add(c.dataset.compare):compared.delete(c.dataset.compare);if(compared.size>3){compared.delete(c.dataset.compare);c.checked=false}renderBattles();renderTable();$("#compare-count").textContent=compared.size})}
function toggleStarter(id){if(lineup[id]){$("#lineup-message").textContent="Use a lineup-card selector to replace a starter; empty positions are prevented.";return}const p=byId(id),slot=settings.slots.find(s=>(p.pos===s||(s==='FLEX'&&settings.flexEligible.includes(p.pos)))&&Object.values(lineup).filter(x=>x===s).length<counts(settings.slots)[s]);if(!slot){$("#lineup-message").textContent=`No open legal ${p.pos} slot. Replace a player from the lineup grid.`;location.hash="#lineup";return}lineup[id]=slot;if(!validate(lineup).ok){delete lineup[id]}save();renderAll()}
function openDetail(id){expanded=id;location.hash="#players";renderTable()}
function renderAll(){renderHeader();renderLineup();renderBattles();renderTable();renderGames();$("#compare-count").textContent=compared.size}
function unique(field){return [...new Set(players.map(p=>p[field]))].filter(Boolean)}
[["#injury-filter","injury"],["#rec-filter","recommendation"],["#confidence-filter","confidence"]].forEach(([sel,f])=>unique(f).forEach(v=>$(sel).insertAdjacentHTML('beforeend',`<option>${v}</option>`)));
$$('.filters input,.filters select').forEach(x=>x.oninput=renderTable);$("#clear-filters").onclick=()=>{$$('.filters input,.filters select').forEach(x=>x.value='');renderTable()};$$('th [data-sort]').forEach(b=>b.onclick=()=>{sort={key:b.dataset.sort,dir:sort.key===b.dataset.sort?-sort.dir:-1};renderTable()});$("#reset").onclick=()=>{lineup={...recommended};save();renderAll()};$("#clear-compare").onclick=()=>{compared.clear();renderAll()};$("#compare-button").onclick=()=>{if(compared.size<2)return;$("#compare-content").innerHTML=`<div class="compare-grid">${[...compared].map(id=>{const p=byId(id);return `<article><h3>${p.name}</h3><p>${p.pos} · ${p.team} · ${p.injury}</p><p><b>Floor / Expected / Ceiling</b><br>${fmt(p.floor)} / ${fmt(p.expected)} / ${fmt(p.ceiling)}</p><p><b>Law of 10:</b> ${p.confidence}<br><b>Role:</b> ${p.role}<br><b>Vegas:</b> ${implied(p).toFixed(2)} implied<br><b>Matchup:</b> #${fmt(p.matchupRank)}<br><b>Risk:</b> ${p.risk}</p></article>`}).join('')}</div>`;$("#compare-dialog").showModal()};$('.dialog-close').onclick=()=>$('#compare-dialog').close();renderAll();
})();
